# K3sNode Vars
nfs_mounts:
  - {
    path: /mnt/hdd/media,
    src: "pi-k3s-admin.local:/mnt/hdd/media",
    fstype: nfs,
    opts: rw, _netdev
  }
  - {
    path: /mnt/hdd/str,
    src: "pi-k3s-admin.local:/mnt/hdd/str",
    fstype: nfs,
    opts: rw, _netdev
  }
  - {
    path: /mnt/hdd/tera,
    src: "pi-k3s-admin.local:/mnt/hdd/tera",
    fstype: nfs,
    opts: rw, _netdev
  }
  - {
    path: /mnt/ssd/pny250,
    src: "pi-k3s-admin.local:/mnt/ssd/pny250",
    fstype: nfs,
    opts: rw, _netdev
  }
