install_ohmyzsh: yes

ssh:
  user: admin

swapSize: 1024

apt:
  - autojump
  - curl
  - git
  - golang-go
  - htop
  - jq
  - libasound2-dev
  - neovim
  - tree
  - wget
  - zsh

directories:
  - ~/.config/nvim
  - ~/.history
  - ~/.go

config_files:
  - { src: ".zshrc", dest: "~/.zshrc" }
  - { src: ".vimrc", dest: "~/.vimrc" }
  - { src: ".bashrc", dest: "~/.bashrc" }
  - { src: "init.vim", dest: "~/.config/nvim/init.vim" }

repos:
  local_dir: ~/git
  sources:
    - { src: 'git@github.com:seemywingz/ponder.git', dest: 'ponder'}

zsh_api_keys:
  - OPENAI_API_KEY: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38386630323239393739323333636530646466343166326535396439663336376632373261623437
          3733386235663166316439616362393338343161616166620a656137343535326336636133303332
          34313938633531616661373036353563373938613362356135386435666131613564323361633030
          3866626464663231340a653139313735346338613263663832633365303438616335633862373531
          33656161373463623139396133316337343734666134633739613139633131613031393033623030
          39623335623362346433626239373733363736356239663866373135326531346532363866653535
          666436343665353366353966643438663862