
# git clone https://github.com/munnerz/kube-plex.git
# helm install plex kube-plex/charts/kube-plex/ \
#   --values values.yml \
#   --namespace media

image:
  repository: linuxserver/plex
  tag: latest
  pullPolicy: Always

kubePlex:
  enabled: false
  image:
    repository: quay.io/munnerz/kube-plex
    tag: latest
    pullPolicy: Always

# Override this with the plex claim token from https://plex.tv/claim
claimToken: "claim-9EFqgBysZ4-_wkq4b1iX" 

# Set the timezone of the plex server
timezone: Europe/London

service:
  type: ClusterIP
  port: 32400
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  ## Use loadBalancerIP to request a specific static IP,
  ## otherwise leave blank
  ##
  loadBalancerIP:
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    cert-manager.io/cluster-issuer: "letsencrypt-prod",
  }
  hosts:
    - plex.livingroom.cloud
  tls: 
    - secretName: plex-livingroom-cloud-tls
      hosts:
        - plex.livingroom.cloud
        
rbac:
  create: true
  # Specify create: false and serviceAccountName to manually manage the service
  # account for this deployment
  ## serviceAccountName: ""

nodeSelector:
  beta.kubernetes.io/arch: arm

persistence:
  transcode:
    # Optionally specify claimName to manually override the PVC to be used for
    # the transcode directory. If claimName is specified, storageClass and size
    # are ignored.
    ## claimName: "plex-transcode-pvc"
    # Optionally specify a storage class to be used for the transcode directory.
    # If not specified and claimName is not specified, the default storage
    # class will be used.
    storageClass: ""
    # subPath: some-subpath
    # The requested size of the volume to be used when creating a
    # PersistentVolumeClaim.
    size: 20Gi
    # Access mode for this volume
    accessMode: ReadWriteMany
  data:
    # Optionally specify claimName to manually override the PVC to be used for
    # the data directory. If claimName is specified, storageClass and size are
    # ignored.
    # claimName: "media-ssd"
    # Optionally specify a storage class to be used for the data directory.
    # If not specified and claimName is not specified, the default storage
    # class will be used.
    storageClass: "hdd-tera-300"
    # subPath: some-subpath
    # The requested size of the volume to be used when creating a
    # PersistentVolumeClaim.
    size: 100Gi
    # Access mode for this volume
    accessMode: ReadWriteMany
  extraData: []
    # Optionally specifify additional Data mounts.  These will be mounted as
    # /data-${name}.  This should be in the same format as the above 'data', 
    # with the additional field 'name'
    # - claimName: "special-tv"
    #   name: 'foo'
  config:
    # Optionally specify claimName to manually override the PVC to be used for
    # the config directory. If claimName is specified, storageClass and size
    # are ignored.
    # claimName: "media-ssd"
    # Optionally specify a storage class to be used for the config directory.
    # If not specified and claimName is not specified, the default storage
    # class will be used.
    # subPath: some-subpath
    storageClass: "ssd-pny250-1"
    # The requested size of the volume to be used when creating a
    # PersistentVolumeClaim.
    size: 1Gi
    # Access mode for this volume
    accessMode: ReadWriteMany

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

podAnnotations: {}

deploymentAnnotations: {}

proxy: 
  # This allows to set a proxy environment variable, which PMS uses to fetch the token and assets like movie cover
  enable: false
  # http: "http://proxy:8080"
  # https: "https://proxy:8080"
  # noproxy: "localhost,127.0.0.1,10.96.0.0/12,10.244.0.0/12"


# allows setting which taints kubeplex tolerates
tolerations: []

# allows specifying node affinity
affinity: {}
