# vim:ft=ansible

- name: Create Directories on Pi
  file: 
    path: "{{item}}"
    state: directory
  with_items:
   - "{{ directories }}"

- name: Copy Config Files to Pi
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - "{{ config_files }}"

- name: Add API Keys to .zshrc
  lineinfile:
    path: ~/.zshrc
    regexp: "export {{ item.key }}="
    line: "export {{ item.key }}=\"{{ item.value }}\""
  with_dict: "{{ zsh_api_keys }}"

- name: Install Oh My ZSH
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
  when: install_ohmyzsh|bool

- name: change user shell to zsh 
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: Generate SSH Key Pair
  openssh_keypair:
    path: ~/.ssh/id_rsa
  when: ssh_keygen|bool

